
CREATE TABLE `appointment` (
  `id` binary(16) NOT NULL,
  `tenant_id` binary(16) NOT NULL,
  `patient_id` binary(16) NOT NULL,
  `service_id` binary(16) DEFAULT NULL,
  `scheduled_at` datetime NOT NULL,
  `duration_minutes` int NOT NULL DEFAULT '30',
  `status` varchar(20) NOT NULL DEFAULT 'SCHEDULED',
  `reason` varchar(500) DEFAULT NULL,
  `staff_notes` text,
  `patient_notes` text,
  `reminder_24h_sent` bit(1) NOT NULL DEFAULT b'0',
  `reminder_2h_sent` bit(1) NOT NULL DEFAULT b'0',
  `confirmed_at` timestamp NULL DEFAULT NULL,
  `cancelled_at` timestamp NULL DEFAULT NULL,
  `cancellation_reason` varchar(500) DEFAULT NULL,
  `parent_appointment_id` binary(16) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` binary(16) DEFAULT NULL,
  `updated_by` binary(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_appt_tenant_datetime` (`tenant_id`,`scheduled_at`),
  KEY `idx_appt_tenant_patient` (`tenant_id`,`patient_id`),
  KEY `idx_appt_tenant_status` (`tenant_id`,`status`),
  KEY `idx_appt_tenant_date_range` (`tenant_id`,`scheduled_at`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `audit_log` (
  `id` binary(16) NOT NULL,
  `action` varchar(50) NOT NULL,
  `details` text,
  `entity_id` binary(16) DEFAULT NULL,
  `entity_name` varchar(255) DEFAULT NULL,
  `entity_type` varchar(50) NOT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `tenant_id` binary(16) NOT NULL,
  `timestamp` datetime(6) NOT NULL,
  `user_email` varchar(255) DEFAULT NULL,
  `user_id` binary(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_audit_tenant_timestamp` (`tenant_id`,`timestamp` DESC),
  KEY `idx_audit_entity` (`tenant_id`,`entity_type`,`entity_id`),
  KEY `idx_audit_user` (`tenant_id`,`user_id`),
  KEY `idx_audit_action` (`tenant_id`,`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `consent_template` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `created_by` binary(16) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `updated_by` binary(16) DEFAULT NULL,
  `tenant_id` binary(16) NOT NULL,
  `active` bit(1) NOT NULL,
  `code` varchar(80) NOT NULL,
  `current_version_id` binary(16) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `display_order` int NOT NULL,
  `name` varchar(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_consent_template_tenant_code` (`tenant_id`,`code`),
  KEY `idx_consent_template_tenant_active` (`tenant_id`,`active`),
  KEY `idx_consent_template_tenant_order` (`tenant_id`,`display_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `consent_template_version` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `created_by` binary(16) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `updated_by` binary(16) DEFAULT NULL,
  `tenant_id` binary(16) NOT NULL,
  `content_html` mediumtext NOT NULL,
  `last_edited_at` datetime(6) DEFAULT NULL,
  `last_edited_by_user_id` binary(16) DEFAULT NULL,
  `published_at` datetime(6) DEFAULT NULL,
  `published_by_user_id` binary(16) DEFAULT NULL,
  `status` enum('ARCHIVED','DRAFT','PUBLISHED') NOT NULL,
  `template_id` binary(16) NOT NULL,
  `title` varchar(300) NOT NULL,
  `version_number` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_consent_version` (`template_id`,`version_number`),
  KEY `idx_consent_version_tenant` (`tenant_id`),
  KEY `idx_consent_version_template_status` (`template_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `medical_photo` (
  `id` binary(16) NOT NULL,
  `tenant_id` binary(16) NOT NULL,
  `patient_id` binary(16) NOT NULL,
  `medical_record_id` binary(16) DEFAULT NULL,
  `appointment_id` binary(16) DEFAULT NULL,
  `photo_type` varchar(20) NOT NULL DEFAULT 'BEFORE',
  `storage_path` varchar(500) NOT NULL,
  `original_filename` varchar(255) DEFAULT NULL,
  `mime_type` varchar(50) DEFAULT NULL,
  `file_size` bigint DEFAULT NULL,
  `captured_at` datetime NOT NULL,
  `anatomical_area` varchar(100) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `consent_given` bit(1) NOT NULL DEFAULT b'0',
  `patient_visible` bit(1) NOT NULL DEFAULT b'0',
  `paired_photo_id` binary(16) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` binary(16) DEFAULT NULL,
  `updated_by` binary(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_photo_tenant_patient` (`tenant_id`,`patient_id`,`captured_at`),
  KEY `idx_photo_tenant_record` (`tenant_id`,`medical_record_id`),
  KEY `idx_photo_tenant_appt` (`tenant_id`,`appointment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `medical_record` (
  `id` binary(16) NOT NULL,
  `tenant_id` binary(16) NOT NULL,
  `patient_id` binary(16) NOT NULL,
  `appointment_id` binary(16) DEFAULT NULL,
  `record_date` datetime NOT NULL,
  `record_type` varchar(30) NOT NULL DEFAULT 'CONSULTATION',
  `title` varchar(200) DEFAULT NULL,
  `content` text NOT NULL,
  `diagnosis` varchar(500) DEFAULT NULL,
  `treatment` text,
  `instructions` text,
  `signed` bit(1) NOT NULL DEFAULT b'0',
  `patient_visible` bit(1) NOT NULL DEFAULT b'0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` binary(16) DEFAULT NULL,
  `updated_by` binary(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_record_tenant_patient` (`tenant_id`,`patient_id`,`record_date`),
  KEY `idx_record_tenant_appt` (`tenant_id`,`appointment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `patient` (
  `id` binary(16) NOT NULL,
  `tenant_id` binary(16) NOT NULL,
  `full_name` varchar(320) NOT NULL,
  `first_name` varchar(80) NOT NULL,
  `middle_name` varchar(80) DEFAULT NULL,
  `last_name` varchar(80) NOT NULL,
  `second_last_name` varchar(80) DEFAULT NULL,
  `email` varchar(160) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `secondary_phone` varchar(20) DEFAULT NULL,
  `document_type` varchar(20) NOT NULL,
  `document_number` varchar(50) NOT NULL,
  `birth_date` date DEFAULT NULL,
  `gender` varchar(1) NOT NULL,
  `nationality` varchar(80) DEFAULT NULL,
  `address` varchar(500) DEFAULT NULL,
  `medical_conditions` text,
  `current_medications` text,
  `allergies` text,
  `blood_type` varchar(5) NOT NULL,
  `emergency_contact_name` varchar(200) NOT NULL,
  `emergency_contact_phone` varchar(20) NOT NULL,
  `emergency_contact_relation` varchar(50) NOT NULL,
  `notes` text,
  `active` bit(1) NOT NULL DEFAULT b'1',
  `photo_consent` bit(1) NOT NULL DEFAULT b'0',
  `data_consent` bit(1) NOT NULL DEFAULT b'0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` binary(16) DEFAULT NULL,
  `updated_by` binary(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_patient_tenant_email` (`tenant_id`,`email`),
  KEY `idx_patient_tenant_document` (`tenant_id`,`document_number`),
  KEY `idx_patient_tenant_active` (`tenant_id`,`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `patient_document` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `created_by` binary(16) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `updated_by` binary(16) DEFAULT NULL,
  `tenant_id` binary(16) NOT NULL,
  `consent_template_id` binary(16) DEFAULT NULL,
  `consent_template_version_id` binary(16) NOT NULL,
  `generated_at` datetime(6) DEFAULT NULL,
  `integrity_hash` varchar(64) DEFAULT NULL,
  `patient_id` binary(16) NOT NULL,
  `pdf_storage_key` varchar(500) DEFAULT NULL,
  `rendered_html` mediumtext NOT NULL,
  `signature_method` varchar(20) DEFAULT NULL,
  `signed_at` datetime(6) DEFAULT NULL,
  `signed_pdf_storage_key` varchar(500) DEFAULT NULL,
  `signer_document` varchar(50) DEFAULT NULL,
  `signer_ip` varchar(45) DEFAULT NULL,
  `signer_name` varchar(250) DEFAULT NULL,
  `signer_user_agent` varchar(500) DEFAULT NULL,
  `staff_user_id` binary(16) DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `template_name` varchar(200) DEFAULT NULL,
  `template_version_number` int DEFAULT NULL,
  `title` varchar(300) NOT NULL,
  `witness_staff_user_id` binary(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pdoc_tenant_patient` (`tenant_id`,`patient_id`),
  KEY `idx_pdoc_tenant_status` (`tenant_id`,`status`),
  KEY `idx_pdoc_tenant_version` (`tenant_id`,`consent_template_version_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `payment_transaction` (
  `id` binary(16) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `currency` varchar(255) NOT NULL,
  `payload_json` longtext,
  `provider` varchar(255) NOT NULL,
  `provider_ref` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL,
  `tenant_id` binary(16) NOT NULL,
  `created_by` binary(16) DEFAULT NULL,
  `updated_by` binary(16) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_pt_provider_ref` (`provider_ref`),
  KEY `idx_pt_tenant_status` (`tenant_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `revoked_token` (
  `jti` varchar(64) NOT NULL,
  `expires_at` datetime(6) NOT NULL,
  `revoked_at` datetime(6) NOT NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_revoked_expires` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `service` (
  `id` binary(16) NOT NULL,
  `tenant_id` binary(16) NOT NULL,
  `name` varchar(200) NOT NULL,
  `description` text,
  `duration_minutes` int NOT NULL DEFAULT '30',
  `price` decimal(10,2) DEFAULT NULL,
  `currency` varchar(3) DEFAULT NULL,
  `active` bit(1) NOT NULL DEFAULT b'1',
  `public_visible` bit(1) NOT NULL DEFAULT b'1',
  `category` varchar(100) DEFAULT NULL,
  `display_order` int NOT NULL DEFAULT '0',
  `requires_photo_consent` bit(1) NOT NULL DEFAULT b'0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` binary(16) DEFAULT NULL,
  `updated_by` binary(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_service_tenant_active` (`tenant_id`,`active`),
  KEY `idx_service_tenant_public` (`tenant_id`,`public_visible`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `signature_request` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `created_by` binary(16) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `updated_by` binary(16) DEFAULT NULL,
  `tenant_id` binary(16) NOT NULL,
  `created_by_staff_user_id` binary(16) NOT NULL,
  `delivery_channel` enum('EMAIL','MANUAL','WHATSAPP') DEFAULT NULL,
  `delivery_error` varchar(500) DEFAULT NULL,
  `delivery_successful` bit(1) DEFAULT NULL,
  `delivery_target` varchar(200) DEFAULT NULL,
  `expires_at` datetime(6) NOT NULL,
  `failed_attempts` int NOT NULL,
  `method` enum('IN_PERSON','REMOTE') NOT NULL,
  `patient_document_id` binary(16) NOT NULL,
  `signed_at` datetime(6) DEFAULT NULL,
  `status` enum('CANCELLED','EXPIRED','PENDING','SIGNED') NOT NULL,
  `token_hash` varchar(64) DEFAULT NULL,
  `witness_staff_user_id` binary(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sigreq_tenant_doc` (`tenant_id`,`patient_document_id`),
  KEY `idx_sigreq_tenant_status` (`tenant_id`,`status`),
  KEY `idx_sigreq_token_hash` (`token_hash`),
  KEY `idx_sigreq_expires_at` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `staff_user` (
  `id` binary(16) NOT NULL,
  `email` varchar(160) NOT NULL,
  `enabled` bit(1) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `role` varchar(20) NOT NULL,
  `tenant_id` binary(16) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` binary(16) DEFAULT NULL,
  `updated_by` binary(16) DEFAULT NULL,
  `mfa_activated_at` datetime(6) DEFAULT NULL,
  `mfa_enabled` bit(1) NOT NULL,
  `mfa_secret` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_staff_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `subscription` (
  `tenant_id` binary(16) NOT NULL,
  `status` varchar(20) NOT NULL,
  `current_period_start` datetime NOT NULL,
  `current_period_end` datetime NOT NULL,
  `last_transaction_id` binary(16) DEFAULT NULL,
  `created_by` binary(16) DEFAULT NULL,
  `updated_by` binary(16) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  PRIMARY KEY (`tenant_id`),
  KEY `idx_subscription_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tenant` (
  `id` binary(16) NOT NULL,
  `alias` varchar(50) NOT NULL,
  `display_name` varchar(200) NOT NULL,
  `contact_email` varchar(160) NOT NULL,
  `contact_phone` varchar(20) DEFAULT NULL,
  `address` varchar(500) DEFAULT NULL,
  `timezone` varchar(50) NOT NULL DEFAULT 'America/Panama',
  `active` bit(1) NOT NULL DEFAULT b'1',
  `settings` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` binary(16) DEFAULT NULL,
  `updated_by` binary(16) DEFAULT NULL,
  `signature_link_hours` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `alias` (`alias`),
  UNIQUE KEY `idx_tenant_alias` (`alias`),
  KEY `idx_tenant_email` (`contact_email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
